### PR TITLE
Upgrade to pip8

### PR DESCRIPTION
**Pull request by glogiotatidis**
To merge after #154

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@akatsoulas r?

**Comment by akatsoulas** [comment]
You have already openede PR #154 for dropping `django-sha2`. Either drop the commit here or close the other PR.

**Comment by glogiotatidis** [comment]
> You have already openede PR #154 for dropping django-sha2. Either drop the commit here or close the other PR.

I'll just wait to merge the other one first! :)

**Comment by akatsoulas** [comment]
Tested this locally and looks good. r+ :+1:

**Comment by glogiotatidis** [comment]
Merci!

**Pull request merged**
