### PR TITLE
Make MozUITour functions available to snippet developers.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@ckprice looks good?

**Comment by bensternthal** [comment]
FYI Cory is on paternity for 2 weeks. He has a new baby!!

:baby: :baby_bottle:

**Comment by Osmose** [comment]
:confetti_ball:

**Comment by glogiotatidis** [comment]
> FYI Cory is on paternity for 2 weeks. He has a new baby!!
woohoo! :dancers: 

this can wait. since Cory is the major snippet developer these days his input is important.

**Comment by glogiotatidis** [comment]
now rebased and ready for review. What do you think @ckprice r?

**Comment by ckprice** [comment]
@glogiotatidis sorry for the delay, and thank you! Quick question: before I dive deep into setting up my local snippet-service environment, are [these](https://abouthome-snippets-service.readthedocs.org/en/latest/contributing.html) docs up to date?

**Comment by glogiotatidis** [comment]
> @glogiotatidis sorry for the delay, and thank you! Quick question: before I dive deep into setting up my local snippet-service environment, are these docs up to date?

Yes! That said, I can push these changes to stage without merging if that's more convenient.

**Comment by ckprice** [comment]
That would be great if it's not too much trouble. I can then create snippets on snippets.allizom to verify these changes. Thanks!

**Comment by glogiotatidis** [comment]
Snippets stage now runs this snippets/mozuitour branch and you can directly test on stage @ckprice

**Comment by ckprice** [comment]
I used https://github.com/mozilla/snippets/pull/56 to r+ this on stage!

**Comment by glogiotatidis** [comment]
Thanks @ckprice :)

**Pull request merged**
