### PR TITLE
Isolate snippet code

### PR DESCRIPTION
**Pull request by koddsson**
This is mostly the work of @Osmose that I took and did very very minor changes to and some rudimentary testing.

Tested on my setup for all even firefox versions in the range >10, <=34 and nightly and can confirm that it does not leak javascript between snippets. I for whatever reason couldn't run any version >=10 on my machine without it crashing :< 

There is one slight drawback to this and it's that for some reason jinja2 (or some component) will escape snippets JSON if you visit a link directly ([like so]( http://localhost:8000/4/Firefox/36.0a1/20141105030203/Darwin_Universal-gcc3/en-US/release/Darwin%2013.4.0/default/default/)) making the JS throw an error and not run the snippet code. I wasn't sure if this is actually a feature we'd like to have or if this regression is OK since it will _not_ escape the JSON if it's loaded into the `about:home` page and therefor works perfectly there.

cc/ @glogiotatidis

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Good stuff, you guys rock! This looks OK but we need to rebase this. I'll take another look and help out this testing when that's done.

**Comment by Osmose** [comment]
I can clean this up and re-submit a PR if @koddsson is busy. Will take a look at this next week if it hasn't already happened. :D

**Comment by Osmose** [comment]
I've updated the branch on my own fork but there's more rebasing to be done, will try to get back to this soon.

**Comment by glogiotatidis** [comment]
@Osmose will you have the time to complete this?

**Comment by Osmose** [comment]
> @Osmose will you have the time to complete this?

In the long run, yes, but I probably won't get back to it for a few weeks. Feel free to take it over if you don't want to wait.

**Comment by glogiotatidis** [comment]
@koddsson @Osmose many thanks for working on this. I continue your work in #128

**Pull request closed without merging**
