### PR TITLE
 [fix bug 1265726] Snippet filtering based on default browser setting. 

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@akatsoulas your time will be payed in beers r?

**Comment by akatsoulas** [comment]
@glogiotatidis much appreciated but I won't be able to review this sooner than Thursday :/

**Comment by glogiotatidis** [comment]
That's cool.

**Comment by akatsoulas** [comment]
Looking good, r+ :+1:

**Pull request merged**
