### PR TITLE
[bug 1233001] Use MLS for all channels. 

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@hannosch How's the MLS service doing with snippets traffic? Are we OK to turn this on for release channel?

**Comment by glogiotatidis** [comment]
This waits for MLS infra updates

**Comment by hannosch** [comment]
We finished stage deployment and tests today, should get the changes out to production later this week.

If all goes well, could we switch over on Monday?

**Comment by glogiotatidis** [comment]
> If all goes well, could we switch over on Monday?

Yes

**Comment by glogiotatidis** [comment]
Also @hannosch do you have any stats to share? Requests per day, peak hours, etc?

**Comment by hannosch** [comment]
Request numbers are pretty low, the two graphs show requests per second and the timezone is UTC. The first is for the last month, the second just for the last day:

mls-country-snippets-month
mls-country-snippets-day

**Comment by hannosch** [comment]
@glogiotatidis we are ready on our side, please go ahead and switch over release channel on Monday.

**Comment by glogiotatidis** [comment]
> @glogiotatidis we are ready on our side, please go ahead and switch over release channel on Monday.

ok!

**Comment by glogiotatidis** [comment]
Switching release :crocodile:

**Pull request merged**
