### PR TITLE
Fix snippet_id in snippet edit and document.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by mozilla-travis** [comment]
```
snippets/base/models.py:202:61: E202 whitespace before ')'

```

**Comment by glogiotatidis** [comment]
@Osmose I remember us talking about this and we agreed to go with `<snippet_id>` because it was less confusing than `{snippet_id}`. Unfortunately this does not go through the XML validator and therefore one cannot save snippets with `<snippet_id>` in either body. I changed that to `[[snippet_id]]` and wrote two lines of documentation. r?

To be on the safe side I checked that no snippet is using `<snippet_id>` on production.

**Comment by mozilla-travis** [comment]
```
snippets/base/models.py:202:61: E202 whitespace before ')'

```

**Comment by Osmose** [comment]
Makes sense to me, r+ :D

**Comment by glogiotatidis** [comment]
Thanks!

**Pull request merged**
