### PR TITLE
 [bug 1217249] Prefetch snippet relations. 

### PR DESCRIPTION
**Pull request by glogiotatidis**
http://www.webpagetest.org/result/151023_VB_GRA/

### CODE REVIEW

**Comment by mozilla-travis** [comment]
```
snippets/base/admin.py:213:1: E303 too many blank lines (3)

```

**Comment by mozilla-travis** [comment]
```
snippets/base/admin.py:213:1: E303 too many blank lines (3)

```

**Comment by glogiotatidis** [comment]
@Osmose This seems to be [working fine](https://bugzilla.mozilla.org/show_bug.cgi?id=1217249#c2). Any comments, tips or additional ideas to make it faster?

**Comment by Osmose** [comment]
Nope, this looks like a fine fix and massively improves the query count for me locally. Nice work!

**Comment by glogiotatidis** [comment]
w00t! thnx!

**Pull request merged**
