### PR TITLE
Add ENV LANG=C.UTF-8 to Dockerfile

### PR DESCRIPTION
**Pull request by jgmize**
This should help with the `UnicodeEncodeError`s we've been seeing.

### CODE REVIEW

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
Thanks Josh! Can you please explain how this fixes the errors?

**Comment by jgmize** [comment]
see https://github.com/docker-library/python/issues/13#issuecomment-56972492 and https://github.com/docker-library/python/pull/14 for more details

**Comment by glogiotatidis** [comment]
Thanks!
Josh Mize writes:

**Pull request merged**
