### PR TITLE
[bug 1129799] Multiple Countries per Snippet

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@pmclanahan r?

**Comment by pmclanahan** [comment]
Kindof a bummer the countries need to be in the DB, but I'm sure this was the easiest way. Code looks good. I'll give it a good run tomorrow and we should be good. Nice work Giorgos. :+1:

**Comment by mozilla-travis** [comment]
```
snippets/base/tests/test_models.py:263:40: E128 continuation line under-indented for visual indent

```

**Comment by glogiotatidis** [comment]
Rebased and updated encoder code due to https://github.com/mozilla/snippets-service/commit/8a0af31e70c97f9ae6fec9cc543446459e820a94

**Comment by pmclanahan** [comment]
WFM. Looks good. Nice work! r+ :cake:

**Pull request merged**
